# Site settings
title: Exotic Stylish
email: info@exotic-stylish.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Exotic stylish leathers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://exotic-stylish.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
